version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/sqsworker
    environment:
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved
    steps:
      - checkout
      - run: go get github.com/jstemmer/go-junit-report
      - run: mkdir -p $TEST_RESULTS
      - run: go test -v -race | tee ${TEST_RESULTS}/go-test.out
      - run: go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml
      - store_test_results:
          path: /tmp/test-results